# Generated by Django 5.0.4 on 2024-04-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='first_field',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='react',
            name='second_field',
            field=models.CharField(max_length=200),
        ),
    ]
